### ISSUE TITLE
markAsBusy / markAsIdle should instantiate idling resources

### ISSUE THREAD

**Issue by zphensley42** [autonomousapps/Cappuccino#2]
I am getting annoyed at those methods not knowing about a resource and having to manually call newIdlingResourceWatcher because I am lazy.

Edit: Some type of policy management similar to StrictMode would be cool. We should to this.

**Comment by trobalik** [comment]
Sounds like a good idea. Just remember that any additions to the public API need to be reflected in the no-op version of the library, as well.
